pollapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from polls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from datetime import timedelta
from django.db import models
from django.db.models import F
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return (timezone.now() > self.pub_date) and (timezone.now() - self.pub_date <= timedelta(days=1))

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def vote(self):
        self.votes = F('votes') + 1
        self.save()

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question, Choice

# Create your views here.


def index(request):
    questions = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    return render(request, 'polls/index.html', {'questions': questions})


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id, pub_date__lte=timezone.now())
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = Question.objects.get(pk=question_id)
    selected_choice = question.choices.get(pk=request.POST['choice'])
    selected_choice.vote()
    return redirect('polls:results', question_id=question_id)

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <h1>Poll App</h1>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    <form method="post" action="{% url 'polls:vote' question.pk %}">
        {% csrf_token %}
        {% for choice in question.choices.all %}
            <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.pk }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Vote</button>
    </form>
    <ul>

        
    </ul>
    
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}
    {% if questions %}
        {% for question in questions %}
            <ul>
                <li><a href="{% url 'polls:detail' question.pk %}">{{ question.question_text }}</a>{{ question.was_published_recently }}</li>
            </ul>
        {% endfor %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choices.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes | pluralize }}</li>
        {% endfor %}
    </ul>


{% endblock %}